# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy-append-test.py
# Created on: 2019-04-29 06:23:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# arcpy test model - test arcpy add for ASLD_OG_LEASES (12,864) leases per add
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
ASLDData_dbo_ASLD_OG_LEASES = "Database Connections\\Connection to localhost ASLDData.sde\\ASLDData.dbo.ASLD_OG_LEASES"
ASLDData_dbo_ASLD_OG_LEASES_FOO__2_ = ASLDData_dbo_ASLD_OG_LEASES
ASLDData_dbo_ASLD_OG_LEASES_FOO = "Database Connections\\Connection to localhost ASLDData.sde\\ASLDData.dbo.ASLD_OG_LEASES_FOO"

# another week goes by ... and the spatial index grows
for x in range(7):
    print(x)
    # Process: Append
    arcpy.Append_management("'Database Connections\\Connection to localhost ASLDData.sde\\ASLDData.dbo.ASLD_OG_LEASES'", ASLDData_dbo_ASLD_OG_LEASES_FOO, "TEST", "", "")

